services:
  db:
    image: postgres:16.13-alpine3.23
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "kemkas"
      POSTGRES_PASSWORD: "kemkas-dev42"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kemkas -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  backend:
    image: ghcr.io/morbalint/kemkas-backend:b8565f8e
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;User Id=kemkas;Password=kemkas-dev42"
      Email__DomainName: "mail.kemkas.hu"
      Email__ApiKey: ""
    depends_on:
      db:
        condition: service_healthy

  proxy:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - $HOME/.aspnet/https/kemkas.pem:/etc/nginx/kemkas.pem
      - $HOME/.aspnet/https/kemkas.key:/etc/nginx/kemkas.key
    depends_on:
      - backend

volumes:
  db-data: