namespace Kemkas.Web.Db.Enums;

public enum Kepzettseg
{
    Alkimia = 1,
    Alcazas = 2,
    Allatidomitas = 3,
    Csapdak = 4,
    Csillagjoslas = 5,
    Egyensulyozas = 6,
    Eloadas = 7,
    Ertekbecsles = 8,
    Gyogyitas = 9,
    Hajozas = 10,
    Hallgatozas = 11,
    Hamisitas = 12,
    JelekOlvasasa = 13,
    Koncentracio = 14,
    Lovaglas = 15,
    Maszas = 16,
    Megfigyeles = 17,
    Meregkeveres = 18,
    Mesterseg = 19,
    Nyomkereses = 20,
    Osonas = 21,
    Rejtozes = 22,
    Szabadulomuveszet = 23,
    Tudas = 24,
    Ugras = 25,
    Uszas = 26,
    Varazslatismeret = 27,
    Zarnyitas = 28,
    Zsebmetszes = 29,
}