name: CI compile & test & build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-fe:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Yarn
      run: |
        cd ./frontend
        yarn install --frozen-lockfiles
        ./compile-less.sh
        yarn test
        yarn build

  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: docker build
      run: |
        cd ./frontend
        docker build .
  
