name: CI compile & test & build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-fe:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - run: |
        cd ./frontend
    - name: install deps
      run: |
        yarn install --frozen-lockfiles
    - name: build css files
      run: |
        ./compile-less.sh
    - name: unit tests
      run: |
        yarn test
    - name: Build
      run: |
        yarn build

  docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: docker build
      run: |
        cd ./frontend
        docker build .
  
